name: 'TS Library'
description: "Build and publish a typescript library"

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '16'
      publish-branch:
        required: false
        type: string
        default: 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install
        run: yarn

      - name: TSC Check
        run: yarn tsc:check

      - name: Test
        run: yarn test

  publish:
    needs: test
    if: github.ref_name == ${{ inputs.publish-branch }}
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: '@getmicro'
      - run: yarn
      - run: yarn build
      - run: yarn publish --patch --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push tag
        run: |
          git push --follow-tags origin